### ISSUE TITLE
A question about using this in long term

### ISSUE THREAD

**Issue by trmdi** [d4rken/wakelock-revamp#13]
First of all I want to say that this is not an issue, just a question. And thank you for your project which help solve my issue.

I have a TX3 mini box. There is a minor issue with it is that when it sleeps then wakes up, it disconnects from the ethernet in about 30s, if Youtube is still running while sleeping, when it wakes up, some icons will be lost.

A workaround is to use wakelock. But the downside is that the CPU seems to run all the time, not so hot, just a bit warm.

The question is: Does it shorten the lifespan of the box in the long term?

**Comment by d4rken** [comment]
> The question is: Does it shorten the lifespan of the box in the long term?

No
